# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  stripeBilling

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  createProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createProduct.createProductHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to create a product in stripe partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /pro
            Method: POST

  createCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createCustomer.createCustomerHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to create a customer in stripe partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /cus
            Method: POST

  createSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createSubscription.createSubscriptionHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to create a subscription in stripe partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /sub
            Method: POST

  updateSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/updateSubscription.updateSubscriptionHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to update a subscription in stripe partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /update
            Method: POST

  subscriptionsListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/subscriptionsList.subscriptionsListHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to fetch list of subscriptions for all customers in a partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /subscriptionsList
            Method: POST

  customersListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/customersList.customersListHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to fetch list of customers in a partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /customersList
            Method: POST

  productsListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/productsList.productsListHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to fetch list of products in a partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /productsList
            Method: POST

    invoicesListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/invoicesList.invoicesListHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to fetch list of invoices in a partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /invoicesList
            Method: POST

    paymentsListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/payments.paymentsListHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 100
      Description: A fuction to fetch list of payments in a partner account

      Events:
        Api:
          Type: Api
          Properties:
            Path: /paymentsList
            Method: POST

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
          - ""
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
          - ""
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      AutoConfigurationEnabled: "true"
    DependsOn: ApplicationResourceGroup
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
